### ISSUE TITLE
 permission denied for window type 2002

### ISSUE THREAD

**Issue by kishanverma26** [noln/system-alert-window-example#1]
`java.lang.RuntimeException: Unable to create service com.mattfenlon.ghost.MainService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@da2ee68 -- permission denied for window type 2002
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3493)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1776)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@da2ee68 -- permission denied for window type 2002
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:952)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.mattfenlon.ghost.MainService.addOverlayView(MainService.java:86)
        at com.mattfenlon.ghost.MainService.onCreate(MainService.java:42)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3483)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1776) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

**Facing issue**

**Comment by noln** [comment]
The flag `TYPE_PHONE` was [deprecated in API level 26](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#TYPE_PHONE). This project predates that release.

Fixed now. @kishanverma26 See the commit history for details.
